language: python

python:
  - 3.6

env:
  - DJANGO=2.1.2

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

script:
  - cd Foodezz
  - python manage.py check
  - coverage run manage.py test

after_success:
  coveralls
